{% set name = "PyDSD" %}
{% set version = "1.0.3.3" %}
{% set sha256 = "1a0de55ad722a52a07635ce18c44edfca87053f11310e2e306b2248e93ffccb3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  #skip: True  # [win]
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - versioneer
  run:
    - python
    - pytmatrix 
    - scipy
    - numpy
    - matplotlib
    - netcdf4


test:
  imports:
    - pydsd

about:
  home: http://github.com/josephhardinee/PyDSD
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  # https://github.com/josephhardinee/PyDSD/pull/59 adds license to source for next release.
  summary: 'Library for working with Disdrometer data, particle probes, and drop size distributions.'

  description: |
    PyDSD is a library for working with disdrometer data, particle
    probes, and drop size distributions. It is pure python.
  doc_url: http://josephhardinee.github.io/PyDSD/
  dev_url: https://github.com/josephhardinee/PyDSD

extra:
  recipe-maintainers:
    - josephhardinee
