{% set name = "PyDSD" %}
{% set version = "1.0.5.2" %}
{% set sha256 = "4623b7cd4771dab726ffd205ab26e8ff5c87b27f584599f98f9648872ee7201f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  #skip: True  # [win]
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - versioneer
    - pip
  run:
    - python
    - pytmatrix 
    - scipy
    - numpy
    - matplotlib-base
    - netcdf4


test:
  imports:
    - pydsd

about:
  home: http://github.com/josephhardinee/PyDSD
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  # https://github.com/josephhardinee/PyDSD/pull/59 adds license to source for next release.
  summary: 'Library for working with Disdrometer data, particle probes, and drop size distributions.'

  description: |
    PyDSD is a library for working with disdrometer data, particle
    probes, and drop size distributions. It is pure python.
  doc_url: http://josephhardinee.github.io/PyDSD/
  dev_url: https://github.com/josephhardinee/PyDSD

extra:
  recipe-maintainers:
    - josephhardinee
