travis:
  secure:
    BINSTAR_TOKEN: BM4lepKebUJYe8k2p783P2r3+GvAMKPV7BY/dNF15Cd+SFWTMSgXiUJ13XAOmdh6Me4JvWPtqgrbC/D0NHT4WnniVqNhPqIK57KECcusB++WncWhMjVImfyrYwXSypbsGgmKSRfT+hp5Rxrzd8bVCRM/Q1gz0PYcOIpOyVv3OqNjT+WmKlI41Sk+eRCkSN45+osiWwgjxMRBTnsNjbNkeWfCjESVdYReaCSO/ixEDqpCLVxNKox1tWlZ4BRZnIRIyt8o6NNpBTxxnCxl4dm15XPjsquz8h1Futl+GvqWbYEg3v4N63Ga4fydOky33vFs0zfqg/Nq6ed+VQWQmPMBROy/XFlcko8FYfBaLSU5zVBAFgg4hu/BcZDwu6sywZu2sTJH8+LvRi61huuCd0OhC48TWJWoizR1F0yOHYgOikO/rMhbGsaJQOTNuQNcVyH7itTeG1Swr1T7oFXLSCZGlcx9lRybXF+jjdawLXrsMVw0PGTNgVAH1vW4Z9aAcNfxOr/UvaKvg/W5QZA1Iw/Pstprx3zd3FzbSL1Q4F2BI44wEK7YoGmC8zNPyQN+jjeh1rhPDCTbzM593a/0nkFyeB5+uANekzSurkd6o7Eabsq3PXYOEAydj3Zgga0I2C3xT42pk5xUKzG/7XIILk9MDUIBQpwMlSKVVdYHhDotK3s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
